services:
  gateway:
    build:
      context: .
      dockerfile: ProductGateway/Dockerfile
    container_name: product_gateway
    restart: unless-stopped
    ports:
      - "7045:7045"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:7045
    depends_on:
      api:
        condition: service_healthy
      frontend:
        condition: service_started

  api:
    build:
      context: .
      dockerfile: ProductApi/Dockerfile
    container_name: product_api
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api:5001/api/products"]
      interval: 5s
      timeout: 3s
      retries: 5

  frontend:
    build:
      context: .
      dockerfile: product-frontend/Dockerfile
    container_name: product_frontend
    restart: unless-stopped
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://api:5001
      - NEXT_PUBLIC_API_URL=http://localhost:5001
