apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-gateway
  template:
    metadata:
      labels:
        app: product-gateway
    spec:
      containers:
      - name: product-gateway
        image: product-gateway:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 7045
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ASPNETCORE_URLS
          value: http://+:7045
---
apiVersion: v1
kind: Service
metadata:
  name: product-gateway
spec:
  type: NodePort
  selector:
    app: product-gateway
  ports:
  - port: 7045
    targetPort: 7045
    nodePort: 30045