apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
    spec:
      containers:
      - name: product-api
        image: product-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ASPNETCORE_URLS
          value: http://+:5001
---
apiVersion: v1
kind: Service
metadata:
  name: product-api
spec:
  type: ClusterIP  # default, internal only
  selector:
    app: product-api
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001