apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-frontend
  template:
    metadata:
      labels:
        app: product-frontend
    spec:
      containers:
      - name: product-frontend
        image: product-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: http://localhost:30045
---
apiVersion: v1
kind: Service
metadata:
  name: product-frontend
spec:
  type: ClusterIP  # default, internal only
  selector:
    app: product-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000